version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: gcloud components update --quiet
      - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${GCP_PROJECT}
      - run: gcloud builds submit --tag gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1 .
      - run: gcloud compute instances update-container instance-1 --container-image gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1


