module Config
  TELEGRAM_TOKEN              = ENV['TELEGRAM_TOKEN'].freeze
  STICKER_COLLECTION_NAME     = ENV['STICKER_COLLECTION_NAME'].freeze
  STICKER_COLLECTION_OWNER_ID = ENV['STICKER_COLLECTION_OWNER_ID'].freeze
end
