# this is a workaround to prevent the Okteto's free tier instance from sleeping
# by default, if no interaction happens within 24 hours, the instance will automatically be put to sleep
name: "Okteto keep awake"
on:
  [push]

  # schedule:
  #   - cron: "* * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: "Activate Namespace"
        uses: okteto/namespace@latest
        with:
          namespace: mathielo
      - name: "Trigger the pipeline"
        uses: okteto/pipeline@latest
        with:
          name: fasd-bot
